### ISSUE TITLE
Single File Components

### ISSUE THREAD

**Issue by ksnyde** [ducksoupdev/vue-webpack-typescript#30]
Was wondering if this template would work with TS and Single File Components. I'm brand new to VUE and my initial attempt failed but it is likely to just where I am on the learning curve.

> Sorry to post this as an issue as it's more of a question

**Comment by ducksoupdev** [comment]
This template is designed for standalone TS files rather than SFC. I would recommend using the official webpack template and tweaking it to add TS support. I have created a repo based on the webpack-simple template to show how to convert it to use Typescript for SFC. You could also make similar changes to the other Vue templates.

https://github.com/ducksoupdev/vue-sfc-ts-simple/compare/v0.1.0...v0.2.0

The creation of an official Typescript template is a hot topic for vue-cli - https://github.com/vuejs/vue-cli/issues/263

Hope this helps?

**Comment by ksnyde** [comment]
Very much so. Thanks.

**Comment by ducksoupdev** [comment]
I have updated the generated template to use Vue v2.5.

Compare the differences: https://github.com/ducksoupdev/vue-sfc-ts-simple/compare/v0.1.0...v0.3.0
